server:
  port: 8088
  servlet:
    context-path: /
  address: 0.0.0.0
spring:
  datasource:
    username: highway_sql
    url: jdbc:mysql://43.138.242.246:3306/highway_sql?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimeZone=Asia/Shanghai
    password: nEkDdBFbWzTsw2Ls
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB     #????????
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.smart_admin.domain
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #??sql??
pagehelper:
  reasonable: false
  defaultCount: true # ?????????? default-count ???????????????????
#privateKeyPath: D:/rsa.pri
#publicKeyPath: D:/rsa.pub
privateKeyPath: /Users/guanziyuan/Documents/biyesheji/highway_vue/jwt/rsa.pri
publicKeyPath: /Users/guanziyuan/Documents/biyesheji/highway_vue/jwt/rsa.pub